# Importar
```{r}
library(nycflights13)
library(tidyverse)
library(tidyverse)
library(gapminder)
library(dplyr)
```
# Archivos a utilizar
```{r}
flights
airports
planes
airlines
weather
```
# 1 Inner-join
```{r}
view(flights)
view(planes)
view(airports)

# 1.1
flights %>%
  inner_join(planes, by = c("tailnum" = "tailnum") )

# 1.2
flights %>%
  inner_join(airlines, by = c("carrier" = "carrier") )

# 1.3
flights %>%
  inner_join(airports, by = c("origin" = "faa") ) %>%
  inner_join(airports, by = c("dest" = "faa") )

# 1.4
flights %>%
  inner_join(weather, by = c("year", "month", "day", "hour", "origin") )


```
# 2 Data manipulation
```{r}
#2.1
flights %>%
  count(year, month, day) %>%
  filter(n > 1000) %>%
  arrange(desc(n))

#2.2
flights_selected <- flights %>%
  select("year" : "day", "hour", "origin", "dest", "tailnum", 'carrier', "arr_delay", "dep_delay")

flights_selected

#2.3
airlines %>%
  left_join(flights_selected, by = c("carrier" = "carrier") ) %>%
  mutate(tot_delay = arr_delay + dep_delay)

#2.4
precip_delay <- flights %>%
  inner_join(weather, by = c("year", "month", "day", "origin", "hour")) %>%
  group_by(precip) %>%
  summarize(delay = mean(dep_delay, na.rm = TRUE)) %>%
  replace_na(list(delay = 0))

precip_delay

#2.5
ggplot(precip_delay, aes(x=precip, y=delay)) +
  geom_point()
```

```{r}
#2.6
flights_airports <- flights %>%
  filter(year == 2013 & month == 5 & day == 10) %>%
  group_by(dest) %>%
  summarize(delay = mean(arr_delay, na.rm =TRUE)) %>%
  inner_join(airports, by = c("dest" = "faa"))

#2.7
ggplot(flights_airports, aes(x=lon, y=lat, color=delay)) + 
  geom_point()


#2.8
flights %>%
  inner_join(planes, by= c("tailnum"), suffix= c("_flights", " _planes")) %>%
  transmute(tailnum, manufacturer, pi = (dep_delay + arr_delay)/air_time )

```


