Condicionales y flujo de control
```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"
toupper("Rchitect") != toupper("rchitect")
tolower("Rchitect") == tolower("rchitect")

(1+2)>4
"dog" > "cat"
TRUE <= FALSE

"raining" <= "table" # lo que hace R, orden alfabetico de las palabras y los compara

TRUE > FALSE
"@" <= "p"
"@" <= "?"

```
Comparar vectores

```{r}
linkedin <- c(16,9,13,5,2,17,14) 
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15 # compara dato por dato de los vectores
facebook <= 10

linkedin > facebook
linkedin == facebook

# para matriz

vistas <- matrix(c(linkedin,facebook), nrow=2, byrow= TRUE)
vistas

vistas == 13
vistas <= 14

```
Operadores logitos

```{r}

TRUE & FALSE
FALSE | TRUE
5 <= 5 & 2 < 3
3 < 4 | 7 < 6


linkedin <= 10 & facebook == 14
linkedin <= 10 & facebook == 7

linkedin <= 10 | facebook == 13


vistas > 11 & vistas < 14
vistas >= 11 | vistas < 4


```
Sentencia IF 
```{r}
media <- "Linkedin"
vista_numeros <- 14

if (media == "linkedin") {
 print("jejje") 
} else if (media == "2Linkedin"){
 print("jejje2")
} else {
  print("tu")
}

if (vista_numeros > 15){
  print("no cumple")
} else {
  print("si cumple")
}



```
While

```{r}
contador <- 0
bandera <- TRUE

while (bandera){
  if(contador == 4){
    bandera <- FALSE
    break
  }
  contador<- contador + 1
  print(contador)
  print(paste("hola.. ", contador)) #concatena
}


```
FOR
```{r}
conteo <- 4
linkedin <- c(16,9,13,5,2,17,14)

for (var in linkedin) {
  if (var == 5){
    print("esto es 5")
    break
  }
  print(var)
}

for (i in 1:length(linkedin)) {
  print(i)
  print(paste("----> ", linkedin[i]))
}

```
LOOP listas

```{r}

nyc <- list(pop=8405837, boroughs = c("Manhattan","Bronx","brooklyn", "Queens", "Staten Insland"), capital=FALSE)

for (x in nyc) {
  print(x)
}

for (x in 1:length(nyc)) {
  if (x == 2){
    for (j in 1:length(nyc[[x]])) {
      print(nyc[[x]][j])
    }
  }
  #print(nyc[x])
}

class(linkedin)
class(nyc)

is.vector(linkedin)

```
LOOP MATRIX

```{r}
vistas <- matrix(c(linkedin,facebook), nrow=2, byrow= TRUE)

for (row in 1:nrow(vistas)) { #recorrer por filas... cada una
  for (col in 1:ncol(vistas)) {
    print(paste("on row", row, "and column", col, "contanins", vistas[row,col]))
  }
}

```


