

```{r}
library(tidyverse)
library(gapminder)
library(dplyr)

gapminder

#resumen 
gapminder %>%
  summarise(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year== 1957) %>%
  summarise(medianLifeExp = median(lifeExp))

gapminder %>%
  filter(year== 1957) %>%
  summarise(medianLifeExp = median(lifeExp), max(gdpPercap))

#group by

gapminder %>%
  group_by(year) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap= max(gdpPercap))

#filter por continente
gapminder %>%
  filter(year == 1957) %>%
  group_by(continent) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap= max(gdpPercap))

# dos group_by
gapminder %>%
  group_by(continent, year) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap= max(gdpPercap))



by_year <- gapminder %>%
  group_by(year) %>%
  summarise(medianLifeExp = median(lifeExp), maxGdpPercap= max(gdpPercap))
  
by_year

# puntos 
ggplot(by_year, aes(x=year, y=medianLifeExp)) + 
  geom_point()

by_year

by_year_continent <- gapminder %>%
  group_by(continent, year) %>%
  summarize(medianLifeExp= median(gdpPercap))

by_year_continent

ggplot(by_year_continent, aes(x= year, y=medianLifeExp, color=continent))+
  geom_point()


```
# tipos de visualización

# Line plots

```{r}
# de tal fecha  al ahora.
# almaceno, agrupo por año y hago la media de gdpPercap
by_year <- gapminder %>%
  group_by(year) %>%
  summarise(medianGdpPercap = median(gdpPercap))

by_year

ggplot(by_year, aes(x=year, y=medianGdpPercap)) +
  geom_line()

# filtro por año y contienen
by_year_continent <- gapminder %>%
  group_by(year, continent) %>%
  summarise(medianGdpPercap = median(gdpPercap))

by_year_continent

ggplot(by_year_continent, aes(x=year, y=medianGdpPercap, color=continent)) +
  geom_line()


```



#bar plots
#variables catergorias vs numericas o continuas
```{r}

oceania_1952 <- gapminder %>%
  filter(continent == "Oceania", year == 1952)
  
oceania_1952

# colour es el contrno, fill es el cuerpo entero

ggplot(oceania_1952, aes(x= country, y=gdpPercap, fill=country )) +
  geom_col()

```
#Histograma

```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952) %>%
  mutate(pop_by_mil = pop / 1000000 )

gapminder_1952

ggplot(gapminder_1952, aes(x= pop_by_mil)) +
  geom_histogram(bins = 50)

# bins  cantidad de rangos en que se divide la grafica


```

```{r}

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop)) +
  geom_histogram(bins=50) +
  scale_x_log10()


  
```

#Blox plots

```{r}
gapminder_1952 <-  gapminder %>%
  filter( year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=continent, y=gdpPercap)) +
  geom_boxplot() +
  scale_y_log10()

```

#data manipulation with dplyr

```{r}
counties <- read_csv(file ="./counties.csv")
counties
```

```{r}
counties %>%
  select(state,county, population, men, women) %>%
  mutate(proportion_men = men/population) %>%
  filter(population > 10000) %>%
  arrange(desc(proportion_men))
```
COUNT
```{r}
counties
counties_selected <- counties %>%
  select(county, region, state, population, citizens)

counties_selected %>%
  count(region, name= "datos", sort =  TRUE)

#que variable establecer el conteo
counties_selected %>%
  count(state, name= "datos", wt=citizens) %>%
  arrange(desc(datos))


counties_selected <- counties %>%
  select(county, region, state, population, citizens, walk)

test <- counties_selected %>%
  mutate(population = population * walk / 100) %>%
  count(state, wt=population, sort=TRUE)

test %>%
  select(state, number=n)



```
summarizing resumen
```{r}

counties_selected <- counties %>%
  select(county,  population, income, unemployment)

counties_selected


counties_selected %>%
  summarise(min_population = min(population), max_unemployment=max(unemployment),
            average_income = mean(income))

counties_selected <- counties %>%
  select(state, county, population, land_area)

counties_selected %>%
  group_by(state) %>%
  summarize(total_area = sum(land_area), total_population = sum(population))

counties_selected <- counties %>%
  select(region, state, county, population)
  
counties_selected %>%
  group_by(region, state) %>%
  summarize(total_pop = sum(population)) %>%
  #ungroup() %>%
  summarize(averange_pop = mean(total_pop), median_pop = median(total_pop))

```
Top_n verb
Top por agrupamientos de los datos.
Cuantos datos queremos ver por agrupamiento.
```{r}

counties_selected <- counties %>%
  select(region, state,  county, metro,  population, walk)

counties_selected %>%
  group_by(region) %>%
  top_n(1, walk)

counties_selected <- counties %>%
  select(region, state, county, population, income)

# agrupando por region y state y el mayor valor por estos group
counties_selected %>%
  group_by(region, state) %>%
  summarise(average_income = mean(income)) %>%
  # dato mas alto de todo los datos en si, sin agrupar.
  # ungroup()%>%
  top_n(1, average_income)


counties_selected <- counties %>%
  select(state, metro,  population)

counties_selected %>%
  group_by(state, metro) %>%
  summarise(total_top = sum(population)) %>%
  top_n(1, total_top) %>%
  ungroup() %>%
  # count(metro)
  count(metro, wt= total_top)

```

