Introducción a Tidyverse
```{r}
library(gapminder)
library(dplyr)
library(ggplot2)
gapminder

# año igual 1957
gapminder %>%
  filter(year == 1957)


#arranging
gapminder %>%
  arrange(lifeExp)

gapminder %>%
  arrange(desc(lifeExp)) #descendente

# filter y arranging
# 
gapminder %>%
  filter(year == 1957) %>%   #filter(year == 1957, continent == "Asia)
  arrange(lifeExp)

# mutate crea una nueva variable o columna

gapminder %>%
  mutate(lifeExp = lifeExp * 2 ) %>%
  arrange(desc(lifeExp))

#Agrega columnas
gapminder %>%
  filter(year == 2007) %>%
  mutate(lifeExpMonts = lifeExp * 12 ) %>%
  arrange(desc(lifeExpMonts))

```


# visualizar con ggplot2

```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>% filter(year == 1952)

gapminder_1952

# grafica de puntos
ggplot(gapminder_1952, aes(x=pop, y= gdpPercap)) + 
  geom_point()

#geom_bar()


```
Log scaling
```{r}
ggplot(gapminder_1952, aes(x=pop, y= gdpPercap)) + 
  geom_point() +
  scale_x_log10() +
  scale_y_log10()


ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent)) + 
  geom_point() + 
  scale_x_log10()

ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent, size=gdpPercap)) + 
  geom_point() +
  scale_x_log10()
```

```{r}

# alt + 126  ~

gapminder_1952
ggplot(gapminder_1952, aes(x=pop, y=lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ continent)

# no continua la variable

ggplot(gapminder, aes(x=gdpPercap, y=lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ year)
```

